main:
  - title: 'Getting Started'
    url: /getting-started/
  - title: 'Blog'
    url: /posts/
  - title: 'Tutorials'
    url: /tutorials/
  - title: 'Documentation'
    url: https://deepspeed.readthedocs.io/
  - title: 'GitHub'
    url: https://github.com/deepspeedai/DeepSpeed

lnav:
  - title: 'Training'
    url: /training/
  - title: 'Inference'
    url: /inference/
  - title: 'Science'
    url: /deepspeed4science/
  - title: 'Getting Started'
    url: /getting-started/
  - title: 'ds_config'
    url: /docs/config-json/
    children:
      - title: 'Autotuning'
        url: /docs/config-json/#autotuning
      - title: 'Batch size'
        url: /docs/config-json/#batch-size-related-parameters
      - title: 'Optimizer'
        url: /docs/config-json/#optimizer-parameters
      - title: 'FP16'
        url: /docs/config-json/#fp16-training-options
      - title: 'BFLOAT16'
        url: /docs/config-json/#bfloat16-training-options
      - title: 'ZeRO optimizations'
        url: /docs/config-json/#zero-optimizations-for-fp16-training
      - title: 'Logging'
        url: /docs/config-json/#logging
      - title: 'Flops Profiler'
        url: /docs/config-json/#flops-profiler
      - title: 'Monitoring'
        url: /docs/config-json/#monitoring-module
      - title: 'Communication Logging'
        url: /docs/config-json/#communication-logging
      - title: 'Data Efficiency'
        url: /docs/config-json/#data-efficiency
  - title: 'Tutorials'
    url: /tutorials/
    children:
      - title: 'Getting started'
        url: /getting-started/
      - title: 'Getting started on Azure'
        url: /tutorials/azure/
      - title: 'Accelerator Abstraction'
        url: /tutorials/accelerator-abstraction-interface/
      - title: 'Accelerator Setup Guides'
        url: /tutorials/accelerator-setup-guide/
      - title: 'Automatic Tensor Parallelism (Inference)'
        url: /tutorials/automatic-tensor-parallelism/
      - title: 'Automatic Tensor Parallelism (Training)'
        url: /tutorials/autotp-training/
      - title: 'Autotuning'
        url: /tutorials/autotuning/
      - title: 'BingBertSQuAD Fine-tuning'
        url: /tutorials/bert-finetuning/
      - title: 'BERT Pre-training'
        url: /tutorials/bert-pretraining/
      - title: 'CIFAR-10'
        url: /tutorials/cifar-10/
      - title: 'Data Efficiency'
        url: /tutorials/data-efficiency/
      - title: 'DeepNVMe'
        url: /tutorials/deepnvme/
      - title: 'Domino'
        url: /tutorials/domino/
      - title: 'DS4Sci_EvoformerAttention'
        url: /tutorials/ds4sci_evoformerattention/
      - title: 'Flops Profiler'
        url: /tutorials/flops-profiler/
      - title: 'PyTorch Profiler'
        url: /tutorials/pytorch-profiler/
      - title: 'GAN'
        url: /tutorials/gan/
      - title: 'Inference'
        url: /tutorials/inference-tutorial/
      - title: 'Learning Rate Range Test'
        url: /tutorials/lrrt/
      - title: 'Megatron-LM GPT2'
        url: /tutorials/megatron/
      - title: 'Mixture of Experts (DeepSpeed MoE)'
        url: /tutorials/mixture-of-experts/
      - title: 'MoE for NLG'
        url: /tutorials/mixture-of-experts-nlg/
      - title: 'MoE Inference'
        url: /tutorials/mixture-of-experts-inference/
      - title: 'Monitoring'
        url: /tutorials/monitor
      - title: 'Communication Logging'
        url: /tutorials/comms-logging
      - title: 'One-Cycle Schedule'
        url: /tutorials/one-cycle/
      - title: 'Pipeline Parallelism'
        url: /tutorials/pipeline/
      - title: 'Transformer Kernel'
        url: /tutorials/transformer_kernel/
      - title: 'Arctic Long Sequence Training (ALST) for HF Transformers integration'
        url: /tutorials/ulysses-alst-sequence-parallelism
      - title: 'ZeRO-Offload'
        url: /tutorials/zero-offload/
      - title: 'ZeRO'
        url: /tutorials/zero/
      - title: 'ZeRO++'
        url: /tutorials/zeropp/
  - title: 'Contributing'
    url: /contributing/
