services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: '8g'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
